name: See Runner

on:
  workflow_dispatch:

jobs:
  see_runner:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: See Runner ( ${{ matrix.runs-on }} )
        run: echo "${{ toJSON(runner) }}"
