name: GitHub Actions Test

on:
  workflow_dispatch:
    inputs:
      case:
        type: choice
        options:
          - show custom error
          - fail 1 (set-failed)
          - fail 2 (error/exit)
          - try exec unknown command
          - set summary

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Show custom error
        if: ${{ inputs.case == 'show custom error' }}
        run: echo "::error::Custom error"\
        
      - name: Fail 1
        if: ${{ inputs.case == 'fail 1 (set-failed)' }}
        run: echo "::set-failed::Error using setFailed"
        
      - name: Fail 2
        if: ${{ inputs.case == 'fail 2 (error/exit)' }}
        run: |
          echo "::error::Error using error/exit"
          exit 1
        
      - name: Try to execute unknown command
        if: ${{ inputs.case == 'try exec unknown command' }}
        run: echo "::unknowncommand::Custom message"

      - name: Set summary
        if: ${{ inputs.case == 'set summary' }}
        run: echo "### Hello world! :rocket:" >> $GITHUB_STEP_SUMMARY
